dist: focal
language: node_js
node_js:
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
  - "21"
install:
  - npm install
script: npm run lint && npm run build && npm test
cache:
  npm: false
